/* action types */

/* export const SET_PRODUCTS = "SET_PRODUCTS";
export const SELECTED_PRODUCTS = "SELECTED_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
 */

export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
};
